services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Monte le répertoire actuel dans /app dans le conteneur
    ports:
      - "23029:8000"  # Expose Django sur le port 23029 (Matricule)
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "24029:5432"  # Expose PostgreSQL sur le port 24029 (Matricule + 1000)

volumes:
  postgres_data:
