services:
  web23029:  # Inclure le matricule
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "23029:8000"
    depends_on:
      - db23029

  db23029:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "24029:5432"

volumes:
  postgres_data:


