# Generated by Django 5.1.4 on 2025-01-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartProducts',
            fields=[
                ('weight', models.FloatField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionproduct.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionproduct.product')),
            ],
        ),
        migrations.DeleteModel(
            name='CartProducts',
        ),
    ]
