# Generated by Django 4.2 on 2025-01-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduct', '0002_partproducts_delete_cartproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartProducts',
            new_name='CartProducts',
        ),
        migrations.RenameField(
            model_name='cartproducts',
            old_name='cart_product',
            new_name='cart',
        ),
        migrations.AlterField(
            model_name='cart',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moughataa',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='pointofsale',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
