# Generated by Django 4.2 on 2025-01-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionproduct', '0003_rename_partproducts_cartproducts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='INPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('inpc_value', models.FloatField()),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
